const galleryImages = [
  {
    title: "Competition",
    images: [
      "Competition/Comp1.jpg",
      "Competition/Comp2.jpg",
      "Competition/Comp3.jpg",
      "Competition/Comp4.jpg",
      "Competition/Comp5.jpg",
      "Competition/Comp6.png",
      "Competition/Comp7.jpg",
      "Competition/Comp8.jpg",
      "Competition/Comp9.jpg",
      "Competition/Comp10.jpg",
      "Competition/Comp11.jpg",
      "Competition/Comp12.jpg",
      "Competition/Comp13.jpg",
      "Competition/Comp14.jpg",
      "Competition/Comp15.jpg",
      "Competition/Comp16.jpg",
      "Competition/Comp17.jpg",
      "Competition/Comp18.jpg",
      "Competition/Comp19.jpg",
      "Competition/Comp20.jpg",
      "Competition/Comp21.jpg",
      "Competition/Comp22.jpg",
      "Competition/Comp23.jpg",
      "Competition/Comp24.png",
      "Competition/Comp25.png",
      "Competition/Comp26.png",
      "Competition/Comp27.png",
      "Competition/Comp28.png",
      "Competition/Comp29.png",
      "Competition/Comp30.png",
    ],
  },
  {
    title: "Manufacturing",
    images: [
      "Manufacturing/man1.png",
      "Manufacturing/man2.png",
      "Manufacturing/man3.png",
      "Manufacturing/man4.png",
      "Manufacturing/man5.jpg",
      "Manufacturing/man6.jpg",
      "Manufacturing/man7.jpg",
      "Manufacturing/man8.png",
      "Manufacturing/man9.png",
      "Manufacturing/man10.png",
      "Manufacturing/man11.png",
      "Manufacturing/man12.jpg",
      "Manufacturing/man13.jpg",
      "Manufacturing/man14.jpg",
      "Manufacturing/man15.jpg",
      "Manufacturing/man16.jpg",
      "Manufacturing/man17.jpg",
      "Manufacturing/man18.png",
      "Manufacturing/man19.jpg",
      "Manufacturing/man20.jpg",
      "Manufacturing/man21.jpg",
      "Manufacturing/man22.jpg",
      "Manufacturing/man23.jpg",
      "Manufacturing/man24.jpg",
      "Manufacturing/man25.jpg",
      "Manufacturing/man26.png",
      "Manufacturing/man27.jpg",
      "Manufacturing/man28.png",
      "Manufacturing/man29.jpg",
    ],
  },
  {
    title: "Teams",
    images: [
      "Teams/Team 2011-12.jpeg",
      "Teams/Team 2012-13.jpeg",
      "Teams/Team 2013-14.jpeg",
      "Teams/Team 2014-15.jpeg",
      "Teams/Team 2016-17.jpeg",
      "Teams/Team 2017-18.jpeg",
      "Teams/Team 2018-19.jpg",
      "Teams/Team 2022-23.png",
      "Teams/Teams 2022-23.jpg",
    ],
  },
  {
    title: "Testing",
    images: [
      "Testing/test1.jpg",
      "Testing/test2.jpg",
      "Testing/test3.jpg",
      "Testing/test4.jpg",
      "Testing/test5.jpg",
      "Testing/test6.jpg",
      "Testing/test7.jpeg",
      "Testing/test8.jpeg",
      "Testing/test9.jpeg",
      "Testing/test10.jpeg",
      "Testing/test11.jpg",
      "Testing/test12.jpg",
      "Testing/test13.jpg",
      "Testing/test14.jpeg",
      "Testing/test15.jpg",
      "Testing/test16.jpg",
      "Testing/test17.jpeg",
      "Testing/test18.jpg",
      "Testing/test19.jpg",
      "Testing/test20.jpg",
      "Testing/test21.jpg",
      "Testing/test22.jpg",
      "Testing/test23.jpg",
      "Testing/test24.jpg",
      "Testing/test25.jpg",
      "Testing/test26.jpg",
    ],
  },
];

export default galleryImages;
